"use client";

import { useState } from "react";
import { SideNav } from "@/components/SideNav";
import { TopBar } from "@/components/TopBar";
import { SeverityBadge } from "@/components/SeverityBadge";
import { cn, timeAgo } from "@/lib/utils";
import { FileText } from "lucide-react";

interface Report {
  id: string;
  title: string;
  summary: string;
  agent: string;
  severity: "critical" | "warning" | "info" | "safe";
  confidence: number;
  timestamp: Date;
  protocols: string[];
  chains: string[];
  content: string;
}

export default function ReportsPage() {
  const [selectedReport, setSelectedReport] = useState<string | null>(null);

  const reports: Report[] = [
    {
      id: "r1",
      title: "DeFi Market Intelligence Brief — May 24, 2026",
      summary:
        "Multi-agent analysis completed. EigenLayer growth notable. Compound flagged for monitoring. Overall risk: LOW.",
      agent: "Analyst",
      severity: "info",
      confidence: 92,
      timestamp: new Date(Date.now() - 600000),
      protocols: ["EigenLayer", "Compound", "Pendle"],
      chains: ["Ethereum", "Arbitrum"],
      content: `# DeFi Intelligence Report — May 24, 2026

## Executive Summary
SentinelPulse multi-agent pipeline completed analysis cycle. The DeFi ecosystem shows continued growth with TVL at $85B+. EigenLayer restaking narrative driving significant inflows.

## Key Findings

### EigenLayer Growth
EigenLayer TVL surged 8.5% over 7 days to $11.2B. Restaking demand continues to outpace expectations. MiMo agents confirm this growth is organic — no anomalous whale concentration detected.

### Compound Alert
Compound TVL declining 2.8% over 7 days. Watchtower agent flagged accelerating decline pattern. Not yet at critical threshold but warrants monitoring. Possible liquidity migration to Morpho and newer lending protocols.

### Pendle Pool Imbalance
Pendle PT-eETH pool showing 12% imbalance. Analyst agent correlates with upcoming maturity event. Not a security concern but indicates informed trading activity.

## Agent Analysis Summary
- **Watchtower**: 3 protocols flagged for elevated monitoring
- **Validator**: No consensus anomalies detected
- **Alert**: 2 whale movements tracked, low risk scores
- **Analyst**: Synthesis complete, confidence 92%

## Risk Assessment
**Overall Threat Level: LOW (23/100)**

All monitored parameters within expected ranges. DeFi ecosystem health: GOOD.

---
*Generated by SentinelPulse Analyst Agent | Powered by Xiaomi MiMo V2.5*`,
    },
    {
      id: "r2",
      title: "Flash Loan Pattern Detection Report",
      summary:
        "Alert agent identified 3 potential flash loan patterns on Ethereum. All within normal MEV activity. No exploit signatures.",
      agent: "Alert",
      severity: "safe",
      confidence: 88,
      timestamp: new Date(Date.now() - 3600000),
      protocols: ["Aave", "Uniswap", "Curve"],
      chains: ["Ethereum"],
      content: `# Flash Loan Activity Report

## Summary
Alert agent processed 2,103 transactions in the last monitoring cycle. Identified 3 flash loan patterns consistent with MEV arbitrage.

## Patterns Detected
1. **Aave → Uniswap → Curve**: WETH/USDC arbitrage, profit $12,400
2. **Aave → Balancer → Uniswap**: WBTC/ETH arbitrage, profit $8,200
3. **dYdX → Uniswap**: USDC/DAI arbitrage, profit $3,100

All patterns show typical MEV characteristics — no exploit signatures detected.

---
*Generated by SentinelPulse Alert Agent | Powered by Xiaomi MiMo V2.5*`,
    },
    {
      id: "r3",
      title: "Oracle Integrity Check — All Chains",
      summary:
        "Validator agent verified oracle feeds across 5 chains. Minor deviation on Arbitrum (1.2%). All other feeds within tolerance.",
      agent: "Validator",
      severity: "info",
      confidence: 95,
      timestamp: new Date(Date.now() - 7200000),
      protocols: ["Chainlink", "Uniswap", "Pyth"],
      chains: ["Ethereum", "Arbitrum", "Base", "Optimism", "Polygon"],
      content: `# Oracle Integrity Report

## Status: ALL CLEAR

Validator agent completed oracle price verification across 5 chains.

## Results
- **Ethereum**: All feeds nominal. Chainlink ↔ Uniswap deviation < 0.1%
- **Arbitrum**: Minor ETH deviation (1.2%). Within 3% threshold.
- **Base**: All feeds nominal. Pyth ↔ Uniswap deviation < 0.5%
- **Optimism**: All feeds nominal
- **Polygon**: All feeds nominal

## Block Health
- No reorgs detected (depth > 1)
- Average block time within 5% of target on all chains
- No consensus anomalies

---
*Generated by SentinelPulse Validator Agent | Powered by Xiaomi MiMo V2.5*`,
    },
  ];

  const active = reports.find((r) => r.id === selectedReport);

  return (
    <div className="flex min-h-screen bg-surface-void">
      <SideNav />
      <div className="flex-1 flex flex-col">
        <TopBar />
        <main className="flex-1 p-4 lg:p-6">
          <div className="mb-6">
            <h1 className="text-2xl font-bold text-text-primary flex items-center gap-2">
              <FileText className="w-6 h-6 text-sentinel-cyan" />
              Agent Reports
            </h1>
            <p className="text-sm text-text-secondary mt-1">
              Intelligence reports generated by MiMo V2.5 agents
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Report List */}
            <div className="space-y-3">
              {reports.map((report) => (
                <button
                  key={report.id}
                  onClick={() => setSelectedReport(report.id)}
                  className={cn(
                    "w-full text-left bg-surface-card rounded-xl p-4 border transition-all",
                    selectedReport === report.id
                      ? "border-sentinel-green/30 shadow-glow-green"
                      : "border-surface-elevated/50 hover:border-surface-elevated"
                  )}
                >
                  <div className="flex items-center gap-2 mb-2">
                    <SeverityBadge level={report.severity} size="sm" />
                    <span className="text-[10px] font-mono text-text-muted">
                      {report.agent}
                    </span>
                  </div>
                  <h3 className="text-sm font-medium text-text-primary mb-1 line-clamp-2">
                    {report.title}
                  </h3>
                  <p className="text-xs text-text-secondary line-clamp-2 mb-2">
                    {report.summary}
                  </p>
                  <div className="flex items-center justify-between">
                    <div className="flex gap-1">
                      {report.protocols.slice(0, 2).map((p) => (
                        <span
                          key={p}
                          className="text-[9px] font-mono text-text-muted bg-surface-elevated px-1 py-0.5 rounded"
                        >
                          {p}
                        </span>
                      ))}
                    </div>
                    <span className="text-[10px] text-text-muted">
                      {timeAgo(report.timestamp)}
                    </span>
                  </div>
                </button>
              ))}
            </div>

            {/* Report Viewer */}
            <div className="lg:col-span-2 bg-surface-card rounded-xl border border-surface-elevated/50 overflow-hidden">
              {active ? (
                <div className="p-6">
                  <div className="flex items-center gap-2 mb-4">
                    <SeverityBadge level={active.severity} />
                    <span className="text-xs text-text-muted">
                      {active.confidence}% confidence
                    </span>
                  </div>
                  <h2 className="text-xl font-bold text-text-primary mb-2">
                    {active.title}
                  </h2>
                  <div className="flex items-center gap-3 mb-6 text-xs text-text-muted">
                    <span>Agent: {active.agent}</span>
                    <span>·</span>
                    <span>{active.timestamp.toLocaleString()}</span>
                    <span>·</span>
                    <span>Chains: {active.chains.join(", ")}</span>
                  </div>
                  <div className="prose prose-invert max-w-none">
                    <pre className="text-sm text-text-secondary whitespace-pre-wrap font-sans leading-relaxed">
                      {active.content}
                    </pre>
                  </div>
                </div>
              ) : (
                <div className="flex items-center justify-center h-96 text-text-muted">
                  <div className="text-center">
                    <FileText className="w-12 h-12 mx-auto mb-3 opacity-30" />
                    <p className="text-sm">Select a report to view</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
